JS: 1-1, 1-2, 1-3
DSTU-frontend-practice-2021/Group-1 pull request #16
Opened 2021-06-29 13:34 UTC by NastyaGnatyuk

2021-06-29 18:53 UTC, iamresp requested changes

2021-06-29 18:53 UTC, iamresp commented on solution/1-2.js
> +let humanYearsCatYearsDogYears = function(humanYears) {
1) Если нигде в дальнейшем значение переменной не планирует использоваться, лучше воспользоваться объявлением через `const`, как в решении 1-1;
2) Но ещё лучше и в этом решении, и в 1-1, объявить функцию так, как в 1-3. По ссылке — комментарий к соседнему пулл реквесту с более подробным объяснением на этот счёт: https://github.com/DSTU-frontend-practice-2021/Group-1/pull/13#discussion_r660871377

2021-06-29 18:53 UTC, iamresp commented on solution/1-2.js
> +  {
На какую строчку ставить фигурную скобку — наверное, один из древнейших холиваров вокруг JS.
Сам склоняюсь, что вот в JS-то точно стоит оставить на той же строке, что и объявление блока или условие. Может, среди коллег есть сторонники обратного.
А вот что бесспорно — важно единообразие. Даже (особенно) в таких мелочах, т. к. разнобой в синтаксисе очень усложняет чтение кода, когда встречается в больших масштабах.
Парой строк выше скобка осталась на той же строке, здесь перенеслась. Нужно выбрать что-то одно.

2021-06-29 18:53 UTC, iamresp commented on solution/1-3.js
> +  return health <= 0 ? false : true;
Здесь напрашивается упрощение :) Однозначно нужно разобраться, что именно будет являться результатом `health <= 0`.

2021-06-29 21:27 UTC, iamresp commented on solution/1-1.js
> +  if (month >= 1 && month <= 3) {
Задачу можно (и однозначно нужно) решить без `if` / `else`. Понадобится выявить одну формулу и воспользоваться округлением вверх — https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/ceil
Такие большие деревья условий всегда являются простейшим способом решить логическую задачу, но являются большой проблемой при поддержке кода — особенно в условиях, когда требования к коду постоянно меняются. Также в подавляющем большинстве случаев, как и здесь, такие большие перечни условий свидетельствуют об упущенной закономерности.

2021-07-02 03:19 UTC, ankormoreankor approved these changes

2021-07-02 03:19 UTC, ankormoreankor commented on solution/1-2.js
> +  return [humanYears, 24 + ((humanYears - 2) * 4), 24 + ((humanYears - 2 )* 5)];
По вашей логике если humanYears === 2, то тут получим [2, 24, 24], то есть то же самое, что в условии выше. Значит оно не нужно. Не стоило слепо копировать у других - эта ошибка повторяется у всех, вы могли стать первой, кто её не допустит.

2021-07-02 03:20 UTC, merged